3.21. Графика для всех страниц
htmlacademy-htmlcss/2016217-sedona-33 pull request #4
Opened 2022-02-08 05:31 UTC by haxenn

4.15. Сетка страниц и крупных блоков на флексах

2022-02-09 08:37 UTC, dean992008 requested changes

2022-02-09 08:37 UTC, dean992008 commented on catalog.html
> +      <div class="catalog-list">
Ты можешь перенести form из 47 строки сюда и использовать его вместо div

2022-02-09 08:37 UTC, dean992008 commented on catalog.html
> +          <span class="visually hidden">Карточки</span>
`visually hidden` -> `visually-hidden`

2022-02-09 08:37 UTC, dean992008 commented on catalog.html
> +  <hr>
Линии это декор, их нужно будет делать на CSS

2022-02-09 08:37 UTC, dean992008 commented on catalog.html
> +        <h3 class="footer-contact-title">+7 (812) 812-12-12</h3>
Телефон не нужно оборачивать в заголовок.

2022-02-09 08:37 UTC, dean992008 commented on catalog.html
> +        <span class="visually hidden">HTML ACADEMY LOGO</span></a></div>
`visually hidden` -> `visually-hidden`

2022-02-09 08:37 UTC, dean992008 commented on catalog.html
> +        <span class="visually hidden">HTML ACADEMY LOGO</span></a></div>
Нужно сделать автоформатирование, сейчас здесь каша.

2022-02-09 08:37 UTC, dean992008 commented on styles/styles.css
> +html {
В этом задании нужно сделать чтобы в случае если контента на странице мало: футер все-равно должен быть прижат к низу страницы. 
Проверить можно времено удалив отели со страницы гостиницы

2022-02-10 22:02 UTC, rereqeqe commented on catalog.html
> +      <div class="catalog-list">
Не совсем понимаю для чего это, использования дива тут это ошибка?

2022-02-11 09:30 UTC, dean992008 commented on catalog.html
> +      <div class="catalog-list">
Фильтры нужно обернуть в форму, и таким образом избавиться от лишних div

2022-02-11 09:32 UTC, dean992008 commented on catalog.html
> +        <h3 class="footer-contact-title">+7 (812) 812-12-12</h3>
Здесь не нужно оборачивать в `p`, просто a и номер телефона.

2022-02-11 09:36 UTC, merged